services:
  zpic:
    container_name: zpic
    image: pub.tcp.mk/helloz/zpic
    networks:
      - baota_net
    ports:
      - "2080:2080"
    volumes:
      - ${APP_PATH}/data:/opt/zpic/app/data
    env_file:
      - .env
    # 环境变量
    environment:
      - WORKERS=2
    depends_on:
      - postgres
      - redis
    restart: always

  postgres:
    container_name: postgres
    image: docker.1ms.run/postgres:17-bookworm
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_PATH}/pgsql/data:/var/lib/postgresql/data
      - ${APP_PATH}/pgsql/postgres.conf:/etc/postgresql/postgresql.conf:ro
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    networks:
      - baota_net

  redis:
    image: docker.1ms.run/redis:8-alpine
    container_name: redis
    networks:
      - baota_net
    restart: always
    volumes:
      - ${APP_PATH}/redis/data:/data
      - ${APP_PATH}/redis/redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]
    
  nsfw:
    container_name: nsfw
    image: pub.tcp.mk/helloz/nsfw
    networks:
      - baota_net
    ports:
      - "6086:6086"
    env_file:
      - .env
    # 环境变量
    environment:
      - TOKEN=${NSFW_TOKEN}
    restart: always

  imgproxy:
    image: pub.tcp.mk/helloz/imgproxy
    container_name: imgproxy
    networks:
      - baota_net
    env_file:
      - .env
    ports:
      - "8088:8080"
    restart: unless-stopped

networks:
  baota_net:
    driver: bridge